version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node

      - xpack.security.enabled=true

      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/config/certs/http.p12
      - xpack.security.http.ssl.truststore.path=/usr/share/elasticsearch/config/certs/http.p12

      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/transport.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/transport.p12

      - ELASTIC_PASSWORD=changeme

      - TZ=Europe/Bucharest

    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - "9200:9200"

    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs

    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    ports:
      - "5601:5601"

    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=JVwm81K0evKt3EwDUtbTDbN1pxjUSWJPFoFTorUGXx8=

      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=password

      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca.crt

      - XPACK_SECURITY_ENABLED=true

    depends_on:
      - elasticsearch

    volumes:
      - ./certs:/usr/share/kibana/config/certs

    networks:
      - elastic

volumes:
  es_data:
    driver: local

networks:
  elastic:
    driver: bridge
